import type { Metadata } from "next";
import {Henny_Penny } from "next/font/google";
import "./globals.css";



const handWritten_Cursive=Henny_Penny({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${handWritten_Cursive.className} antialiased  `}
      >
        {children}
      </body>
    </html>
  );
}
